# See NetworkManager.conf(5)

[main]
plugins=keyfile
dhcp=internal
# DNS is handled by dnsmasq + dnscrypt-proxy through a static /etc/resolv.conf
dns=none
rc-manager=unmanaged
hostname-mode=none

[connection]
# New MAC address every boot on wired and wireless connections
wifi.cloned-mac-address=stable
ethernet.cloned-mac-address=stable
connection.stable-id=${BOOT}
# Only take effect if dns= is ever changed from none
ipv4.dns-priority=-100
ipv4.ignore-auto-dns=true
ipv6.dns-priority=-100
ipv6.ignore-auto-dns=true
# Don't send the hostname to DHCP servers
ipv4.dhcp-send-hostname=false
ipv6.dhcp-send-hostname=false

[device]
wifi.scan-rand-mac-address=yes
