monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-Topping_D50_III-00"
      }
    ]
    actions = {
      update-props = {
        api.alsa.use-acp = false
        api.acp.auto-profile = false
        device.profile = "on"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.usb-Topping_D50_III-00.playback.0.0"
      }
    ]
    actions = {
      update-props = {
        api.alsa.period-size   = 512
        api.alsa.period-num    = 4
        api.alsa.headroom      = 256
        api.alsa.batch         = false
        audio.format           = "S32LE"
        audio.rate             = 0
        audio.channels         = 2
        resample.disable       = true
        channelmix.disable     = true
        dither.disable         = true
        node.pause-on-idle     = false
        node.volume            = 1.0
        node.mute              = false
        session.suspend-timeout-seconds = 0
        priority.driver        = 2000
        priority.session       = 2000
      }
    }
  }
]
