# /etc/security/limits.conf

# System-wide limits
*               soft    nofile          524288
*               hard    nofile          524288
*               soft    nproc           32768
*               hard    nproc           131072
*               soft    memlock         unlimited
*               hard    memlock         unlimited
*               soft    rtprio          90
*               hard    rtprio          90
*               soft    sigpending      32768
*               hard    sigpending      65536
*               soft    stack           32768
*               hard    stack           65536
*               soft    as              unlimited
*               hard    as              unlimited
*               soft    cpu             unlimited
*               hard    cpu             unlimited
*               soft    data            unlimited
*               hard    data            unlimited
*               soft    fsize           unlimited
*               hard    fsize           unlimited
*               soft    locks           65536
*               hard    locks           131072
*               soft    msgqueue        819200
*               hard    msgqueue        819200
*               soft    rss             unlimited
*               hard    rss             unlimited

# Real-time limits
*               soft    rttime          200000
*               hard    rttime          unlimited

# Audio group
@audio          -       nice           -20
@audio          -       rtprio          90
@audio          soft    memlock         unlimited
@audio          hard    memlock         unlimited
@audio          soft    nofile          524288
@audio          hard    nofile          1048576
@audio          soft    rttime          200000
@audio          hard    rttime          200000
@audio          soft    nproc           131072
@audio          hard    nproc           262144

# Video group
@video          -       nice           -10
@video          -       rtprio          80
@video          soft    memlock         unlimited
@video          hard    memlock         unlimited
@video          soft    nofile          524288
@video          hard    nofile          524288

# Render group
@render         -       nice           -5
@render         -       rtprio          75
@render         soft    memlock         unlimited
@render         hard    memlock         unlimited
@render         soft    nofile          524288
@render         hard    nofile          524288
